### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by Orcomp** [LeifUK/OpenControls.Wpf#4]
Looks like there is a file missing:

![image](https://user-images.githubusercontent.com/2459973/108579583-c2204b00-737b-11eb-91be-bd4c71e4824c.png)

**Comment by LeifUK** [comment]
Are you sure? I can see it in the GIT repository and in my local respoitories.

**Comment by Orcomp** [comment]
Yes, I did a direct clone of the repo and it didn't build.

I see there are some new commits that have fixed the issue. Thanks!
