### ISSUE TITLE
Missing Type ConfigurationSerialiser

### ISSUE THREAD

**Issue by StephanWeber79** [LeifUK/OpenControls.Wpf#6]
Hello,

in the Project OpenControls.WinForms.SurfacePlotterDemo the ConfigurationSerialiser is missing.

But the first look: nice work!

**Comment by LeifUK** [comment]
Apologies, this has now been fixed. Thanks for finding this issue. Please download the changes and let me know if there are any problems.

**Comment by StephanWeber79** [comment]
Works, thank you!

**Comment by LeifUK** [comment]
Awesome!
