### ISSUE TITLE
Docking like VSCode

### ISSUE THREAD

**Issue by APerricone** [LeifUK/OpenControls.Wpf#7]
Sorry, it is not properly an issue but I need help.

I would like to do an interface like VSCode using your dockManager, that mean:
 * don't allow to make document floating 
* don't show the cross of buttons when move a document

This gif show the result I would like to reach: ![VSCode sample](https://code.visualstudio.com/assets/docs/getstarted/userinterface/grid-dnd.gif)
is  it possible?

**Comment by APerricone** [comment]
I did it in [my fork](https://github.com/APerricone/OpenControls.Wpf), I did it hammering but it works 🙂

**Comment by LeifUK** [comment]
Glad you managed it. Removing the cross buttons is easy, the other requirement less so.
